version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.dev:/app/.env  # Mount the .env.dev file as .env inside the container
    environment:
      - NODE_ENV=development
      - SERVICE_ENV=dev
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
